# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider :filoo do |filoo|
    
    filoo.filoo_api_key = "your filoo api access key" 
    # or to use environment variable uncomment this
    #filoo.filoo_api_key = ENV['FILOO_API_KEY']
    
    filoo.filoo_api_entry_point = "https://api.filoo.de/api/v1" 
    # or to use environment variable uncomment this
    #filoo.filoo_api_entry_point = ENV['FILOO_API_ENTTRY_POINT'] 
    
    filoo.cd_image_name = "Debian 7.7 - 64bit"
    filoo.type =  "dynamic"
    filoo.cpu = 1
    filoo.ram = 128
    filoo.hdd = 10
  end
  
  #TODO shell Provisioner 
  #ifconfig eth1
end
